import mongoose from "mongoose";

const restrictionSchema = new mongoose.Schema({
    id:{
        type:String,
        required:true
    },
    isIntact:{
        type:Boolean,
        required:true,
        default:true
    },
    target:{
        vibeId:{
            type:mongoose.Schema.Types.ObjectId,
            required:false
        },
        communityId:{
            type:mongoose.Schema.Types.ObjectId,
            required:false
        },
        venueId:{
            type:mongoose.Schema.Types.ObjectId,
            required:false
        },
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            required:true
        },
        required:true
    },
    source:{
        platform:{
            type:Boolean,
            required:true
        },
        venue:{
            type:Boolean,
            required:false
        },
        artist:{
            type:Boolean,
            required:true
        },
        community:{
            type:Boolean,
            required:true
        },
        required:true
    },
    contents:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:false
        },
        required:true
    },
    execution:{
        penalty:{
            mute:{
                type:Boolean,
                required:false
            },
            ban:{
                vibe:{
                    type:Boolean,
                    required:false
                },
                community:{
                    type:Boolean,
                    required:false
                },
                venue:{
                    type:Boolean,
                    required:false
                },
                artist:{
                    type:Boolean,
                    required:false
                },
                required:false
            },
            required:true
        },
        duration:{
            deployment:{
                type:Date,
                required:true
            },
            suspension:{
                type:Date,
                required:false
            },
            termination:{
                agent:{
                    type:mongoose.Schema.Types.ObjectId,
                    required:true
                },
                date:{
                    type:Date,
                    required:true
                },
                required:false
            },
            required:true
        },
        breachSource:{
            posts:[{
                type:mongoose.Schema.Types.ObjectId,
                ref:'message'
            }],
            visibility:{
                type:Boolean,
                required:true,
                default:true
            },
            required:true
        },
        required:false
    }

})

const Restriction = mongoose.models.Restriction || mongoose.model('Restriction', restrictionSchema)
export default Restriction